### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Karlatemp** [NLR-DevTeam/GrassPictures#1]
1. [x] HttpClient 未复用

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L95
https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L173
https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/GrassPic.java#L35
https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/GrassPic.java#L70

----

2. [x] 应该使用 `JvmPlugin.getDataFolder()` 而不是直接硬编码绝对路径, 以及变量名命名不规范

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/GrassPic.java#L64

and more...

```java
File directory = new File(INSTANCE.getDataFolder(), "cache/grasspic/");
// .....


File savedImage = new File(directory, id);
Files.copy(/**/, savedImage.toPath());

return savedImage;
```

----
3. [x] 未使用线程安全的集合类型

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L26-L29

mirai 是多线程模型, 需要考虑并发执行的情况

-------

其他建议:

- 可以考虑使用线程池而不是到处 `new Thread`
- 不建议使用 `Thread.stop` 而是使用 中断 `Thread.interrupt`

并发:

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L37-L39
https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L61-L64

```
if (nextAreYou.remove(m.getSender().getId()) == null) return;
```

---

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/PostGrassPic.java#L27

> 指的是 `<User>` 泛型: see https://github.com/mamoe/mirai/issues/585
 
-----

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/commands/GrassPic.java#L33-L55

如果最后都要检查是不是 null, 我建议不如干脆直接抛出一个 RuntimeException

-----

https://github.com/NLR-DevTeam/GrassPictures/blob/1f154bbba6d26588094aab6e4b286525cdd3572c/src/main/java/cn/whitrayhb/grasspics/Cooler.java#L9-L39

通用的实现方法是创建一个 `Map</*id*/ Long, /* timestamp */ Long>`

然后 lock 方法直接  `put(id, System.currentTimeMillis())`

```
isLocked(long id) {
Long value = map.get(id);
if (value == null) return false;
return System.currentTimeMills() - value <= 1000L;
}
````

当然我建议使用 [guava](https://github.com/google/guava) 的 [Cache](https://github.com/google/guava/blob/c34a1cf3dbc7baaf2b5820316adae67f3794c65b/guava/src/com/google/common/cache/CacheBuilder.java#L103-L116) 指定过期时间, 实现起来更加简单, 并且解决了内存释放的问题

**Comment by XIAYM-gh** [comment]
感谢提这么多建议
我明天火速改

但是我觉得那个地方好像只能用 Thread.stop()， interrupt()方法并不会中断代码执行
我想要实现的效果就是强制取消发送
本人理解不充分 可能会有错()

**Comment by Karlatemp** [comment]
Thread.stop 永远是最坏的情况下才使用的

如果代码已经自行到 mirai 发送信息了，那么就不应该执行中断了

mirai 内部会分配一些资源到当前线程，如果正好这个时候强行 stop 了，谁也不知道会引发什么问题
http client 基本都会处理中断请求的, 基本上只要请求中断了就会中断 http 请求

**Comment by XIAYM-gh** [comment]
好的 多谢

**Comment by XIAYM-gh** [comment]
问一个我很难解决的问题（）
怎么把项目目标Java版本设置到17（
我尝试了各种方法 但都在Gradle编译时报错了

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/tree/dev/mirai-console/tools/gradle-plugin#%E9%85%8D%E7%BD%AE

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/tree/dev/mirai-console/tools/gradle-plugin#%E9%85%8D%E7%BD%AE

**Comment by XIAYM-gh** [comment]
谢

**Comment by XIAYM-gh** [comment]
改进了大部分代码，剩的几个有点难实现，我去研究下怎么搞（

**Comment by Karlatemp** [comment]
看了一下最新的修改，有这些问题

            Path cachePicturePath = Paths.get(file + jsonObject.getString("id"));

file.toString() 是不带 / 结尾的, 具体怎么做上面有
以及这个方法的返回类型我建议改成 File, 因为你最后使用也得 new File


            if (listeningThreads.containsKey(uid)) { 
                 listeningThreads.get(uid).interrupt(); 
                 listeningThreads.remove(uid); 
             }

> 我指的全部这种模式的并发类型操作

你应该直接 var listener = .remove(uid);
然后判断 listener 是不是 null

如果你担心变量名污染，可以使用大括号包装一下，如

{
  var listener = ...
  if (listener != null) {
  }
}

在并发中没人能保证执行 contains 后的一瞬间是不是就被其他线程移除了

以及 cooler 那也应该 get 出来后判空, 而不是先判断 contians 再 get
